#!/usr/bin/env python3
"""Generates res/layout/widget_host.xml: the widget's RemoteViews host — a full-bleed canvas
ImageView plus a ROWS x COLS grid of transparent, weighted `View`s (ids `hit_r_c`) used as
click targets for free-placement elements. See widget/HitGrid.kt for how element rects map onto
these cells, and widget/WidgetUpdater.kt for how PendingIntents are attached.

The grid is inlined directly into the host (no <include>, which is unreliable in RemoteViews)
and kept deliberately coarse: every cell is a real View in the RemoteViews the launcher must
inflate, and every *claimed* cell adds a PendingIntent to the Binder transaction, so an
oversized grid risks "problem loading widget". 12x12 balances tap precision against payload size.

Run from the repo root: `python scripts/gen_hit_grid.py`
"""
import pathlib

ROWS = 12
COLS = 12
OUT = pathlib.Path(__file__).resolve().parent.parent / "app/src/main/res/layout/widget_host.xml"

# Cells are ImageView, NOT the bare View class: RemoteViews only inflates a fixed set of view
# types in the launcher's process, and plain <View> is not among them — using it made the whole
# widget fail to inflate ("problem loading widget"). ImageView is RemoteViews-supported (the
# previous widget system used it for its tap cells too).
CELL = (
    '                <ImageView\n'
    '                    android:id="@+id/hit_{r}_{c}"\n'
    '                    android:layout_width="0dp"\n'
    '                    android:layout_height="match_parent"\n'
    '                    android:layout_weight="1"\n'
    '                    android:background="@android:color/transparent"\n'
    '                    android:contentDescription="@null" />\n'
)

ROW_OPEN = (
    '            <LinearLayout\n'
    '                android:layout_width="match_parent"\n'
    '                android:layout_height="0dp"\n'
    '                android:layout_weight="1"\n'
    '                android:orientation="horizontal">\n'
)
ROW_CLOSE = '            </LinearLayout>\n'


def build():
    out = []
    out.append('<?xml version="1.0" encoding="utf-8"?>\n')
    out.append('<!-- GENERATED by scripts/gen_hit_grid.py — do not edit by hand. -->\n')
    out.append('<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"\n')
    out.append('    android:id="@+id/widget_root"\n')
    out.append('    android:layout_width="match_parent"\n')
    out.append('    android:layout_height="match_parent">\n\n')
    out.append('    <ImageView\n')
    out.append('        android:id="@+id/iv_canvas"\n')
    out.append('        android:layout_width="match_parent"\n')
    out.append('        android:layout_height="match_parent"\n')
    out.append('        android:scaleType="fitXY"\n')
    out.append('        android:contentDescription="@null" />\n\n')
    out.append('    <LinearLayout\n')
    out.append('        android:layout_width="match_parent"\n')
    out.append('        android:layout_height="match_parent"\n')
    out.append('        android:orientation="vertical">\n')
    for r in range(ROWS):
        out.append(ROW_OPEN)
        for c in range(COLS):
            out.append(CELL.format(r=r, c=c))
        out.append(ROW_CLOSE)
    out.append('    </LinearLayout>\n')
    out.append('</FrameLayout>\n')
    return "".join(out)


if __name__ == "__main__":
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(build(), encoding="utf-8")
    print(f"wrote {OUT} ({ROWS}x{COLS} cells, inlined host)")
